---
stages:
- build

variables:
  GIT_SUBMODULE_STRATEGY: normal

build-dev:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh", "-c"]
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  when: manual
  except:
  - tags

build-prod:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh", "-c"]
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"$REGISTRY\":{\"auth\":\"$REGISTRY_TOKEN\"}}}" > ~/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  only:
  - tags
