version: '2'

services:
  taiga:
    build: .
    ports:
      - 8080:80
    volumes:
      - './taiga-back:/usr/src/taiga-back'
      - './docker-entrypoint.sh:/docker-entrypoint.sh'
      - './docker-settings.py:/usr/src/taiga-back/settings/docker.py'
    environment:
      TAIGA_HOSTNAME: localhost:8080
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_HOST: postgres
      TAIGA_DB_USER: postgres
      TAIGA_DB_PASSWORD: password
      TAIGA_SLEEP: 0

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432
